#!/bin/bash
# determine operating system
#
OS=`uname`
echo "OPERATING SYSTEM IS: $OS"

HOST=`hostname`

if [[ $OS == 'Darwin' ]]; then

  export MPIDIR=/usr/local

elif [[ $OS == 'Linux' ]]; then
  if [[ $HOST == 'shuttle' ]]; then
      export MPIDIR=/local/tmp/oneapi/mpi/2021.1.1
  else
      export MPIDIR=/opt/intel/oneapi/mpi/2021.1.1
  fi

else
  echo "Error! System not detected!"
fi

export SCRATCHDIR=Compile
export SRCDIR=../src


MPI=0
Test=0

if [[ $MPI == 1 ]]; then
  CFT=mpiifort
  MPIINC="-I$MPIDIR/include"
  LFLAGS="-L$MPIDIR/lib -lmpi"
else
  CFT=gfortran
  MPIINC=""
  LFLAGS=""
fi

rm -rf ${SCRATCHDIR}
mkdir ${SCRATCHDIR}

cp -f  ${SRCDIR}/*.f90    $SCRATCHDIR
cp -f  ${SRCDIR}/Makefile $SCRATCHDIR

if [[ $CFT == ifort ]]; then
  . /local/tmp/oneapi/setvars.sh 
  if [[ $Test == 1 ]]; then
     echo 'Run model with debug options...'
     #FFLAGS="-O0 -r8 -i4 -g -check all -fpe-all=0 -nowarn -traceback -debug extended -nogen-interface -warn interfaces"
     FFLAGS="-O0 -r8 -i4 -g -check all -fpe-all=0 -fp-model=precise -nowarn -traceback -debug all -gen-interface"
  else
     FFLAGS="-O3 -xHost -r8 -i4 -fp-model=precise"
     echo 'Run model without debug options...'
  fi
elif [[ $CFT == mpiifort ]] || [[ $CFT ==  mpifort ]]; then
  . /local/tmp/oneapi/setvars.sh 
  if [[ $Test == 1 ]]; then
     echo 'Using mpi with debug options...'
     FFLAGS="-O0 -r8 -i4 -g -check all -fpe-all=0 -fp-model=precise -nowarn -traceback -debug all -gen-interface"
     #FFLAGS="-O0 -g -fdefault-real-8 -fdefault-double-8 -fimplicit-none -Wall -Wline-truncation  -Wcharacter-truncation  -Wsurprising  -Waliasing  -Wimplicit-interface  -Wunused-parameter  -fwhole-file  -fcheck=all  -std=f2008  -pedantic  -fbacktrace"
     #FFLAGS="-O0 -g -fdefault-real-8 -fdefault-double-8 -fimplicit-none -Wno-all -Wno-line-truncation  -Wno-character-truncation  -Wno-surprising  -Wno-aliasing  -Wno-implicit-interface  -Wno-unused-parameter  -fwhole-file  -fcheck=all  -std=f2008  -pedantic  -fbacktrace"
  else
     FFLAGS="-O3 -xHost -r8 -i4 -fp-model=precise"
     #FFLAGS="-O3 -fdefault-real-8 -fdefault-double-8 -march=native -fimplicit-none -Wall  -Wline-truncation  -fwhole-file -ffinite-math-only -std=f2008 -fstrength-reduce"
     echo 'Using mpi without debug options...'
  fi
elif [[ $CFT == pgfortran ]]; then
  if [[ $Test == 1 ]]; then
     echo 'Run model with debug options...'
     FFLAGS="-Mbounds -Minfo=all -traceback -Mchkfpstk -Mchkstk -Mdalign 
-Mdclchk -Mdepchk -Miomutex -Mrecursive -Msave -Ktrap=fp -O0 -g -byteswapio"
  else
     FFLAGS="-fast -Mipa=fast,inline"
     echo 'Run model without debug options...'
  fi
elif [[ $CFT == gfortran ]]; then
  if [[ $Test == 1 ]]; then
     echo 'Run model with debug options...'
     FFLAGS="-O0 -g -fdefault-real-8 -fdefault-double-8 -fimplicit-none -Wall -Wline-truncation  -Wcharacter-truncation  -Wsurprising  -Waliasing  -Wimplicit-interface  -Wunused-parameter  -fwhole-file  -fcheck=all  -std=f2008  -pedantic  -fbacktrace"
  else
     FFLAGS="-O3  -fdefault-real-8 -fdefault-double-8 -march=native -fimplicit-none -Wall  -Wline-truncation  -fwhole-file  -std=f2008"
     echo 'Run model without debug options...'
  fi
else
  
  echo "Unknown Fortran compiler"
	exit
fi

export LD_LIBRARY_PATH=/local/tmp/oneapi/compiler/2021.1.1/linux/compiler/lib/intel64_lin/

FFLAGS="$FFLAGS $MPIINC"
cd ${SCRATCHDIR}
echo 's?$(FFLAGS)?'$FFLAGS'?g' >> flags.tmp
export MAKEFILE=Makefile
sed -f flags.tmp $MAKEFILE > Makefile2
rm -rf flags.tmp

echo 's?$(CFT)?'$CFT'?g' >> flags.tmp
sed -f flags.tmp Makefile2 > Makefile3
rm -rf flags.tmp
echo 's?$(LFLAGS)?'$LFLAGS'?g' >> flags.tmp
sed -f flags.tmp Makefile3 > Makefile
make
rm -rf flags.tmp

mv IBM ../
cd ../
